{
  imports = [
    ./astrophotography.nix
    ./browser.nix
    ./btop/btop.nix
    ./common.nix
    ./dev.nix
    ./direnv.nix
    ./email.nix
    ./fortune.nix
    ./games.nix
    ./gaming.nix
    ./git.nix
    ./imv.nix
    ./kitty.nix
    ./media.nix
    ./mpv.nix
    ./music.nix
    ./neovim
    ./yazi.nix
    ./zathura.nix
  ];
}
