# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/569a5044-8c75-41a1-ad5b-f5ccf3d7e1e5";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/516D-8A5B";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/4tb" =
    { device = "/dev/disk/by-uuid/4850DDDA50DDCF36";
      fsType = "ntfs";
    };

  fileSystems."/mnt/win" =
    { device = "/dev/disk/by-uuid/CA3646E93646D5DB";
      fsType = "ntfs";
    };

  fileSystems."/mnt/ssd1" =
    { device = "/dev/disk/by-uuid/648CD8628CD83072";
      fsType = "ntfs";
    };

  fileSystems."/mnt/ssd2" =
    { device = "/dev/disk/by-uuid/90C8CBFBC8CBDD9A";
      fsType = "ntfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/1c8d568c-387e-40e3-90f2-69982f5b09c2"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
