#!/usr/bin/env bash

images_path=~/wallpapers/
image=$(shuf -n1 -e $images_path*)
pgrep swww > /dev/null || swww init
swww img $image --transition-type grow --transition-pos 0.9,0.1 --transition-duration 1.5 --transition-fps 90
